//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vexease.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vexease.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 命令提示符 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnCmd {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制台 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnConsole {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制面板 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnCtrlPnl {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnCtrlPnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程管控 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnProcCtrl {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnProcCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerShell 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnPS {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册表 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnRegustry {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnRegustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行工具 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnRunTool {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnRunTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统盘管控 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnSys {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务管理器 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_BtnTaskMgr {
            get {
                return ResourceManager.GetString("AdmFormCtrl_BtnTaskMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置管理 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_LblOptimization {
            get {
                return ResourceManager.GetString("AdmFormCtrl_LblOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统状态 的本地化字符串。
        /// </summary>
        internal static string AdmFormCtrl_LblStatus {
            get {
                return ResourceManager.GetString("AdmFormCtrl_LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap black {
            get {
                object obj = ResourceManager.GetObject("black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btn1 {
            get {
                object obj = ResourceManager.GetObject("btn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap btn2 {
            get {
                object obj = ResourceManager.GetObject("btn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CheckBtnClose {
            get {
                object obj = ResourceManager.GetObject("CheckBtnClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CheckBtnOpen {
            get {
                object obj = ResourceManager.GetObject("CheckBtnOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap half {
            get {
                object obj = ResourceManager.GetObject("half", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap half1 {
            get {
                object obj = ResourceManager.GetObject("half1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap half2 {
            get {
                object obj = ResourceManager.GetObject("half2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 
        /// 的本地化字符串。
        /// </summary>
        internal static string ListViewSetByName_SetCompare_LF {
            get {
                return ResourceManager.GetString("ListViewSetByName_SetCompare_LF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ListViewSetByName_Warning {
            get {
                return ResourceManager.GetString("ListViewSetByName_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您未选择任何项。 的本地化字符串。
        /// </summary>
        internal static string ListViewSetByPath_EditItem_NoSelect {
            get {
                return ResourceManager.GetString("ListViewSetByPath_EditItem_NoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码！ 的本地化字符串。
        /// </summary>
        internal static string LoginForm_LoginForm_Load_ {
            get {
                return ResourceManager.GetString("LoginForm_LoginForm_Load_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码！ 的本地化字符串。
        /// </summary>
        internal static string LoginForm_TxtPwd_input_ {
            get {
                return ResourceManager.GetString("LoginForm_TxtPwd_input_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空！ 的本地化字符串。
        /// </summary>
        internal static string LoginFormCtrl_PwdSet_BeNull {
            get {
                return ResourceManager.GetString("LoginFormCtrl_PwdSet_BeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请再次输入密码！ 的本地化字符串。
        /// </summary>
        internal static string LoginFormCtrl_PwdSet_InputAgain {
            get {
                return ResourceManager.GetString("LoginFormCtrl_PwdSet_InputAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入不一致！ 的本地化字符串。
        /// </summary>
        internal static string LoginFormCtrl_PwdSet_NotSimible {
            get {
                return ResourceManager.GetString("LoginFormCtrl_PwdSet_NotSimible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码！ 的本地化字符串。
        /// </summary>
        internal static string PwdChangeForm_PwdChangeForm_Input {
            get {
                return ResourceManager.GetString("PwdChangeForm_PwdChangeForm_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请再次输入密码！ 的本地化字符串。
        /// </summary>
        internal static string PwdChangeForm_PwdChangeForm_InputAgain {
            get {
                return ResourceManager.GetString("PwdChangeForm_PwdChangeForm_InputAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap QQ图片20170928165258 {
            get {
                object obj = ResourceManager.GetObject("QQ图片20170928165258", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Set {
            get {
                object obj = ResourceManager.GetObject("Set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 启用中 的本地化字符串。
        /// </summary>
        internal static string UserFormCtrl_StatusChange_启用中 {
            get {
                return ResourceManager.GetString("UserFormCtrl_StatusChange_启用中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已禁用 的本地化字符串。
        /// </summary>
        internal static string UserFormCtrl_StatusChange_已禁用 {
            get {
                return ResourceManager.GetString("UserFormCtrl_StatusChange_已禁用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已作出以下修改：
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string WListSetFormCtrl_SetCompare_01 {
            get {
                return ResourceManager.GetString("WListSetFormCtrl_SetCompare_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///已删除：
        /// 的本地化字符串。
        /// </summary>
        internal static string WListSetFormCtrl_SetCompare_02 {
            get {
                return ResourceManager.GetString("WListSetFormCtrl_SetCompare_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///  确认修改吗？
        /// 的本地化字符串。
        /// </summary>
        internal static string WListSetFormCtrl_SetCompare_03 {
            get {
                return ResourceManager.GetString("WListSetFormCtrl_SetCompare_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///已添加：
        /// 的本地化字符串。
        /// </summary>
        internal static string WListSetFormCtrl_SetCompare_04 {
            get {
                return ResourceManager.GetString("WListSetFormCtrl_SetCompare_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认修改 的本地化字符串。
        /// </summary>
        internal static string WListSetFormCtrl_SetCompare_确认修改 {
            get {
                return ResourceManager.GetString("WListSetFormCtrl_SetCompare_确认修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 背景 {
            get {
                object obj = ResourceManager.GetObject("背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
